#
# This file is part of the xPack project (http://xpack.github.io).
# Copyright (c) 2023 Liviu Ionescu. All rights reserved.
#
# This Software is provided under the terms of the MIT License.
# If a copy of the license was not distributed with this file, it can
# be obtained from https://opensource.org/licenses/MIT/.
#
# -----------------------------------------------------------------------------

name: CI on Push

on:
  push:

jobs:
  ci-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [ ubuntu-22.04, macos-12 ]
        node-version: [ 18 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 3

    - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install xpm
      run: npm install --global xpm@latest

    - name: Satisfy project dependencies
      run: xpm install

    - name: Run test
      run: xpm run test

