#
# This file is part of the xPack project (http://xpack.github.io).
# Copyright (c) 2023 Liviu Ionescu. All rights reserved.
#
# This Software is provided under the terms of the MIT License.
# If a copy of the license was not distributed with this file, it can
# be obtained from https://opensource.org/licenses/MIT/.
#
# -----------------------------------------------------------------------------

name: Manual

on:
  workflow_dispatch:
    inputs:
      xpm_version:
        description: 'The version of xpm to install'
        required: false
        type: string
        default: 'latest'

jobs:
  manual-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [ ubuntu-22.04, macos-12 ]
        node-version: [ 18 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 3

    - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install xpm
      run: npm install --global xpm@${{ github.event.inputs.xpm_version }}

    - name: Pretend no xPack project
      run: rm -f package*.json

    - name: Make project an xPack
      run: xpm init

    - name: Add dependencies
      run: xpm install @xpack-dev-tools/clang@16.0.6-1.1 @xpack-dev-tools/cmake@3.26.5-1.1 @xpack-dev-tools/ninja-build@1.11.1-3.1

    - name: Adjust PATH
      run: echo "$(pwd)/xpacks/.bin" >> $GITHUB_PATH

    - name: Build
      run: |
        cmake -S . -B build -G Ninja -D CMAKE_TOOLCHAIN_FILE=cmake/clang.cmake
        cmake --build build --verbose

    - name: Run test
      run: cd build && ctest -V
